name: CI - Heart Disease MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mlflow-run:
    runs-on: ubuntu-latest

    env:
      MLFLOW_CONDA_CREATE_ENV: false
      MLFLOW_USE_CONDA: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run . --no-conda
