name: MLflow CI Basic

on:
  push:
    branches: [ "main" ]

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # 3. Check Environment
    - name: Check Env
      run: |
        python --version
        pip --version
        echo "Working directory:"
        pwd

    # 4. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    # 5. Run MLflow Project
    - name: Run MLflow Project
      run: |
        mlflow run MLProject

    # 6. Get latest MLflow run_id
    - name: Get latest MLflow run_id
      run: |
        mlflow runs list --max-results 1
