name: mlflow-ci

on:
  push:
    branches: [ main ]

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        env:
          MLFLOW_CONDA_CREATE_ENV: "false"
          MLFLOW_USE_CONDA: "false"
        run: mlflow run .
